// Mocks generated by Mockito 5.4.4 from annotations
// in ecommerce_elevate/test/features/address/address_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:ecommerce_elevate/core/datasource_execution/results.dart'
    as _i12;
import 'package:ecommerce_elevate/domain/entities/addresses/request/add_address_request.dart'
    as _i14;
import 'package:ecommerce_elevate/domain/entities/addresses/response/address.dart'
    as _i13;
import 'package:ecommerce_elevate/domain/repository/addresses_repository.dart'
    as _i5;
import 'package:ecommerce_elevate/domain/use_case/add_new_address_use_case.dart'
    as _i11;
import 'package:geocode/src/geocode.dart' as _i9;
import 'package:geocode/src/model/address.dart' as _i3;
import 'package:geocode/src/model/coordinates.dart' as _i4;
import 'package:location/location.dart' as _i6;
import 'package:location_platform_interface/location_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocationData_0 extends _i1.SmartFake implements _i2.LocationData {
  _FakeLocationData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddress_1 extends _i1.SmartFake implements _i3.Address {
  _FakeAddress_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCoordinates_2 extends _i1.SmartFake implements _i4.Coordinates {
  _FakeCoordinates_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressesRepository_3 extends _i1.SmartFake
    implements _i5.AddressesRepository {
  _FakeAddressesRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Location].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocation extends _i1.Mock implements _i6.Location {
  MockLocation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i2.LocationData> get onLocationChanged => (super.noSuchMethod(
        Invocation.getter(#onLocationChanged),
        returnValue: _i7.Stream<_i2.LocationData>.empty(),
      ) as _i7.Stream<_i2.LocationData>);

  @override
  _i7.Future<bool> changeSettings({
    _i2.LocationAccuracy? accuracy = _i2.LocationAccuracy.high,
    int? interval = 1000,
    double? distanceFilter = 0.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeSettings,
          [],
          {
            #accuracy: accuracy,
            #interval: interval,
            #distanceFilter: distanceFilter,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> isBackgroundModeEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBackgroundModeEnabled,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> enableBackgroundMode({bool? enable = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #enableBackgroundMode,
          [],
          {#enable: enable},
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i2.LocationData> getLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [],
        ),
        returnValue: _i7.Future<_i2.LocationData>.value(_FakeLocationData_0(
          this,
          Invocation.method(
            #getLocation,
            [],
          ),
        )),
      ) as _i7.Future<_i2.LocationData>);

  @override
  _i7.Future<_i2.PermissionStatus> hasPermission() => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [],
        ),
        returnValue: _i7.Future<_i2.PermissionStatus>.value(
            _i2.PermissionStatus.granted),
      ) as _i7.Future<_i2.PermissionStatus>);

  @override
  _i7.Future<_i2.PermissionStatus> requestPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i7.Future<_i2.PermissionStatus>.value(
            _i2.PermissionStatus.granted),
      ) as _i7.Future<_i2.PermissionStatus>);

  @override
  _i7.Future<bool> serviceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #serviceEnabled,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> requestService() => (super.noSuchMethod(
        Invocation.method(
          #requestService,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i2.AndroidNotificationData?> changeNotificationOptions({
    String? channelName,
    String? title,
    String? iconName,
    String? subtitle,
    String? description,
    _i8.Color? color,
    bool? onTapBringToFront,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeNotificationOptions,
          [],
          {
            #channelName: channelName,
            #title: title,
            #iconName: iconName,
            #subtitle: subtitle,
            #description: description,
            #color: color,
            #onTapBringToFront: onTapBringToFront,
          },
        ),
        returnValue: _i7.Future<_i2.AndroidNotificationData?>.value(),
      ) as _i7.Future<_i2.AndroidNotificationData?>);
}

/// A class which mocks [GeoCode].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoCode extends _i1.Mock implements _i9.GeoCode {
  MockGeoCode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i7.Future<_i3.Address> reverseGeocoding({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #reverseGeocoding,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue: _i7.Future<_i3.Address>.value(_FakeAddress_1(
          this,
          Invocation.method(
            #reverseGeocoding,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i7.Future<_i3.Address>);

  @override
  _i7.Future<_i4.Coordinates> forwardGeocoding({required String? address}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forwardGeocoding,
          [],
          {#address: address},
        ),
        returnValue: _i7.Future<_i4.Coordinates>.value(_FakeCoordinates_2(
          this,
          Invocation.method(
            #forwardGeocoding,
            [],
            {#address: address},
          ),
        )),
      ) as _i7.Future<_i4.Coordinates>);
}

/// A class which mocks [AddNewAddressUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddNewAddressUseCase extends _i1.Mock
    implements _i11.AddNewAddressUseCase {
  MockAddNewAddressUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.AddressesRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAddressesRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.AddressesRepository);

  @override
  set repository(_i5.AddressesRepository? _repository) => super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i12.Results<List<_i13.Address>?>> call(
    _i14.AddAddressRequest? request,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            request,
            token,
          ],
        ),
        returnValue: _i7.Future<_i12.Results<List<_i13.Address>?>>.value(
            _i10.dummyValue<_i12.Results<List<_i13.Address>?>>(
          this,
          Invocation.method(
            #call,
            [
              request,
              token,
            ],
          ),
        )),
      ) as _i7.Future<_i12.Results<List<_i13.Address>?>>);
}
