name: ecommerce_elevate
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl:
  bloc:
  flutter_bloc:
  shared_preferences:
  provider:
  injectable:
  get_it:
  retrofit:
  logger: ^2.4.0
  json_annotation:
  dio:
  lottie:
  dialogs:
    git:
      url: https://github.com/john-safwat/My-Packages.git
      path: app_packages/dialogs
  pretty_dio_logger:
  connectivity_plus:
  cached_network_image: ^3.4.1
  animate_do:
  icons_launcher:
  flutter_native_splash:
  mockito:
  location:
  geocode:
  skeletonizer:
  import_sorter:
  fluttertoast:

import_sorter:
  emojis: true # Optional, defaults to false
  comments: true # Optional, defaults to true

dev_dependencies:
  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
  retrofit_generator: ">=8.0.0 <10.0.0" # for Dart 3.3 use ^9.0.0
  json_serializable:

  location_platform_interface: any
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
