// Mocks generated by Mockito 5.4.4 from annotations
// in ecommerce_elevate/test/features/auth/presentation/signup/signup_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

// 🎯 Dart imports:
import 'dart:async' as _i3;

// 📦 Package imports:
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

import 'package:ecommerce_elevate/core/datasource_execution/results.dart'
    as _i4;
import 'package:ecommerce_elevate/features/auth/domain/entities/registration/registration_response.dart'
    as _i5;
import 'package:ecommerce_elevate/features/auth/domain/entities/registration/registration_user.dart'
    as _i6;
import 'package:ecommerce_elevate/features/auth/domain/use_case/signup_user_use_case.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SignupUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupUserUseCase extends _i1.Mock implements _i2.SignupUserUseCase {
  MockSignupUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Results<_i5.RegistrationResponse>> call(
          _i6.RegistrationUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [user],
        ),
        returnValue: _i3.Future<_i4.Results<_i5.RegistrationResponse>>.value(
            _i7.dummyValue<_i4.Results<_i5.RegistrationResponse>>(
          this,
          Invocation.method(
            #call,
            [user],
          ),
        )),
      ) as _i3.Future<_i4.Results<_i5.RegistrationResponse>>);
}
