// Mocks generated by Mockito 5.4.4 from annotations
// in ecommerce_elevate/test/data/repository/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ecommerce_elevate/core/datasource_execution/results.dart'
    as _i5;
import 'package:ecommerce_elevate/data/datasource/impl/auth_local_datasource_impl.dart'
    as _i17;
import 'package:ecommerce_elevate/data/datasource/impl/auth_remote_datasource_impl.dart'
    as _i3;
import 'package:ecommerce_elevate/domain/entities/authentication/authentication_request.dart'
    as _i10;
import 'package:ecommerce_elevate/domain/entities/authentication/authentication_response.dart'
    as _i9;
import 'package:ecommerce_elevate/domain/entities/change_password/change_password_reaponse.dart'
    as _i15;
import 'package:ecommerce_elevate/domain/entities/change_password/change_password_request.dart'
    as _i16;
import 'package:ecommerce_elevate/domain/entities/forgetPassword/forget_password_response.dart'
    as _i11;
import 'package:ecommerce_elevate/domain/entities/registration/registration_response.dart'
    as _i6;
import 'package:ecommerce_elevate/domain/entities/registration/registration_user.dart'
    as _i7;
import 'package:ecommerce_elevate/domain/entities/reset_password/reset_password_request.dart'
    as _i14;
import 'package:ecommerce_elevate/domain/entities/reset_password/reset_password_response.dart'
    as _i13;
import 'package:ecommerce_elevate/domain/entities/verify_reset_code/verify_reset_code_response.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasourceImpl extends _i1.Mock
    implements _i3.AuthRemoteDatasourceImpl {
  MockAuthRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Results<_i6.RegistrationResponse>> signup(
          _i7.RegistrationUser? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [user],
        ),
        returnValue: _i4.Future<_i5.Results<_i6.RegistrationResponse>>.value(
            _i8.dummyValue<_i5.Results<_i6.RegistrationResponse>>(
          this,
          Invocation.method(
            #signup,
            [user],
          ),
        )),
      ) as _i4.Future<_i5.Results<_i6.RegistrationResponse>>);

  @override
  _i4.Future<_i5.Results<_i9.AuthenticationResponse>> signIn(
          _i10.AuthenticationRequest? auth) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [auth],
        ),
        returnValue: _i4.Future<_i5.Results<_i9.AuthenticationResponse>>.value(
            _i8.dummyValue<_i5.Results<_i9.AuthenticationResponse>>(
          this,
          Invocation.method(
            #signIn,
            [auth],
          ),
        )),
      ) as _i4.Future<_i5.Results<_i9.AuthenticationResponse>>);

  @override
  _i4.Future<_i5.Results<_i11.ForgetPasswordResponse>> forgetPassword(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue: _i4.Future<_i5.Results<_i11.ForgetPasswordResponse>>.value(
            _i8.dummyValue<_i5.Results<_i11.ForgetPasswordResponse>>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i5.Results<_i11.ForgetPasswordResponse>>);

  @override
  _i4.Future<_i5.Results<_i12.VerifyResetCodeResponse>> verifyResetCode(
          String? resetCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [resetCode],
        ),
        returnValue:
            _i4.Future<_i5.Results<_i12.VerifyResetCodeResponse>>.value(
                _i8.dummyValue<_i5.Results<_i12.VerifyResetCodeResponse>>(
          this,
          Invocation.method(
            #verifyResetCode,
            [resetCode],
          ),
        )),
      ) as _i4.Future<_i5.Results<_i12.VerifyResetCodeResponse>>);

  @override
  _i4.Future<_i5.Results<_i13.ResetPasswordResponse>> resetPassword(
          _i14.ResetPasswordRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue: _i4.Future<_i5.Results<_i13.ResetPasswordResponse>>.value(
            _i8.dummyValue<_i5.Results<_i13.ResetPasswordResponse>>(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i4.Future<_i5.Results<_i13.ResetPasswordResponse>>);

  @override
  _i4.Future<_i5.Results<_i15.ChangePasswordResponse?>> changePassword(
    String? token,
    _i16.ChangePasswordRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            token,
            request,
          ],
        ),
        returnValue:
            _i4.Future<_i5.Results<_i15.ChangePasswordResponse?>>.value(
                _i8.dummyValue<_i5.Results<_i15.ChangePasswordResponse?>>(
          this,
          Invocation.method(
            #changePassword,
            [
              token,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Results<_i15.ChangePasswordResponse?>>);
}

/// A class which mocks [AuthLocalDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDatasourceImpl extends _i1.Mock
    implements _i17.AuthLocalDatasourceImpl {
  MockAuthLocalDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i2.SharedPreferences);

  @override
  set sharedPreferences(_i2.SharedPreferences? _sharedPreferences) =>
      super.noSuchMethod(
        Invocation.setter(
          #sharedPreferences,
          _sharedPreferences,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> storeToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #storeToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
