// Mocks generated by Mockito 5.4.4 from annotations
// in ecommerce_elevate/test/data/repository/categories_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ecommerce_elevate/core/datasource_execution/results.dart'
    as _i4;
import 'package:ecommerce_elevate/data/datasource/contract/categories_remote_datasource.dart'
    as _i2;
import 'package:ecommerce_elevate/domain/entities/category/category.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoriesRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoriesRemoteDatasource extends _i1.Mock
    implements _i2.CategoriesRemoteDatasource {
  MockCategoriesRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Results<List<_i5.Category>?>> getCategoriesList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesList,
          [],
        ),
        returnValue: _i3.Future<_i4.Results<List<_i5.Category>?>>.value(
            _i6.dummyValue<_i4.Results<List<_i5.Category>?>>(
          this,
          Invocation.method(
            #getCategoriesList,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Results<List<_i5.Category>?>>);
}
