// Mocks generated by Mockito 5.4.4 from annotations
// in ecommerce_elevate/test/features/home/data/datasource/impl/products_remote_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ecommerce_elevate/features/home/data/api/products/products_retrofit_client.dart'
    as _i4;
import 'package:ecommerce_elevate/features/home/data/models/products/all_products_respons_dto.dart'
    as _i3;
import 'package:ecommerce_elevate/features/home/data/models/products/best_seller_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBestSellerResponseDto_0 extends _i1.SmartFake
    implements _i2.BestSellerResponseDto {
  _FakeBestSellerResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAllProductsResponsDto_1 extends _i1.SmartFake
    implements _i3.AllProductsResponsDto {
  _FakeAllProductsResponsDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsRetrofitClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRetrofitClient extends _i1.Mock
    implements _i4.ProductsRetrofitClient {
  MockProductsRetrofitClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.BestSellerResponseDto> getBestSellerList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBestSellerList,
          [],
        ),
        returnValue: _i5.Future<_i2.BestSellerResponseDto>.value(
            _FakeBestSellerResponseDto_0(
          this,
          Invocation.method(
            #getBestSellerList,
            [],
          ),
        )),
      ) as _i5.Future<_i2.BestSellerResponseDto>);

  @override
  _i5.Future<_i3.AllProductsResponsDto> getAllProducts({
    String? occasionId,
    String? categoryId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
          {
            #occasionId: occasionId,
            #categoryId: categoryId,
          },
        ),
        returnValue: _i5.Future<_i3.AllProductsResponsDto>.value(
            _FakeAllProductsResponsDto_1(
          this,
          Invocation.method(
            #getAllProducts,
            [],
            {
              #occasionId: occasionId,
              #categoryId: categoryId,
            },
          ),
        )),
      ) as _i5.Future<_i3.AllProductsResponsDto>);
}
